version: "3"
services: 
  mysql:
    container_name: todo-list-mysql
    image: mysql:latest
    ports: 
      -"3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DB=todolist

volumes:
  db_data: ~